"""Output terms and patterns that should never appear in end-user analysis copy."""

BANNED_TERMS = {
    "cheating",
    "cheater",
    "faithful",
    "unfaithful",
    "lie",
    "lying",
    "liar",
    "dishonest",
    "dishonesty",
    "truth",
    "truthful",
    "secretly",
    "passed",
    "failed",
    "hired",
    "rejected",
    "guilty",
    "innocent",
    "manipulation",
    "manipulative",
    "manipulate",
    "proves",
    "proof",
    "guaranteed",
    "deceptive",
    "deception",
    "secretive",
    "betrayal",
    "betrayed",
    "infidelity",
    "affair",
    "flirting",
    "gaslighting",
    "toxic",
    "abusive",
    "narcissist",
    "autism",
    "adhd",
    "neurotype",
}

BANNED_PATTERNS = (
    r"\bbreak up with\b",
    r"\byou should leave\b",
    r"\bthey should be fired\b",
    r"\bthis means they are\b",
    r"\bthis suggests they are\b",
    r"\bthis indicates they are\b",
    r"\bthis implies they are\b",
    r"\bthis points to\b",
    r"\bevidence of\b",
    r"\bstrong sign of\b",
    r"\bappears to show\b",
    r"\bthey lied\b",
    r"\bthey cheated\b",
    r"\bthey (?:are|were|seem|seemed) manipulating you\b",
    r"\bhidden motive\b",
    r"\bhidden intent\b",
    r"\bthey like you\b",
    r"\bthey secretly\b",
    r"\bthey secretly want\b",
    r"\bmake them\b",
    r"\bpressure them\b",
    r"\bwin them back\b",
    r"\battachment style\b",
    r"\bemotional truth\b",
    r"\btruth about how they feel\b",
    r"\bcover[\s-]?up\b",
    r"\bconceal(?:ed|ment)?\b",
    r"\bexpose(?:d)?\b",
    r"\bcaught\b",
    r"\bsuspicious(?:ly)?\b",
    r"\bred flag[s]?\b",
    r"\bpass the interview\b",
    r"\bfail the interview\b",
    r"\bget the job\b",
    r"\bwon'?t get the job\b",
    r"\bdiagnos",
    r"\blegal action\b",
    r"\bwill happen\b",
)
