"""Output terms and patterns that should never appear in end-user analysis copy."""

BANNED_TERMS = {
    "cheating",
    "cheater",
    "faithful",
    "unfaithful",
    "lie",
    "lying",
    "liar",
    "dishonest",
    "dishonesty",
    "truth",
    "truthful",
    "passed",
    "failed",
    "hired",
    "rejected",
    "guilty",
    "innocent",
    "manipulation",
    "manipulative",
    "proves",
    "proof",
    "deceptive",
    "deception",
    "secretive",
    "betrayal",
    "betrayed",
    "infidelity",
    "affair",
    "flirting",
    "gaslighting",
    "toxic",
    "abusive",
}

BANNED_PATTERNS = (
    r"\bbreak up with\b",
    r"\byou should leave\b",
    r"\bthey should be fired\b",
    r"\bthis means they are\b",
    r"\bthis suggests they are\b",
    r"\bthis indicates they are\b",
    r"\bthis implies they are\b",
    r"\bthis points to\b",
    r"\bevidence of\b",
    r"\bstrong sign of\b",
    r"\bappears to show\b",
    r"\bhidden intent\b",
    r"\bcover[\s-]?up\b",
    r"\bconceal(?:ed|ment)?\b",
    r"\bexpose(?:d)?\b",
    r"\bcaught\b",
    r"\bsuspicious(?:ly)?\b",
    r"\bred flag[s]?\b",
    r"\bpass the interview\b",
    r"\bfail the interview\b",
    r"\bget the job\b",
    r"\bwon'?t get the job\b",
    r"\bdiagnos",
    r"\blegal action\b",
    r"\bwill happen\b",
)
